name: Vestaboard

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - name: Send message to Vestaboard
        run: npm start
        env:
          VESTABOARD_TOKEN: ${{ secrets.VESTABOARD_TOKEN }}
